#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#~/.config/polybar/./launch.sh &
#picom &

xrandr --output DP-1 --primary --left-of HDMI-1 
/usr/bin/feh --bg-fill /home/sebz/Desktop/fondos/redGirl.jpg

#bspc monitor -d I II III IV V VI VII VIII IX X 

bspc monitor DP-1 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 9 10

~/.config/polybar/./launch.sh &
picom &

bspc config border_width         0
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a * desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

wmname LG3D &
#bspc config border_width 0
